Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.image = "postgres"
        d.ports = ["6032:5432"]
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
end
