Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.image = "cassandra:2.2.4"
        d.ports = ["9160:9160", "9042:9042", "7000:7000", "7001:7001", "7199:7199"]
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
end
